npmPublishRegistry: 'https://registry.npmjs.org/'

npmRegistries:
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: 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

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@3o3/mystique-components@*':
    dependencies:
      react-is: ^17
  '@3o3/react@*':
    dependencies:
      react-dom: ^17.0.2
  '@cspotcode/source-map-support@*':
    dependencies:
      source-map-support: '*'
  babel-preset-react-app@*:
    dependencies:
      '@babel/plugin-proposal-private-property-in-object': '*'
  local-pkg@*:
    dependencies:
      happy-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.4.cjs
