version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: <TASK_DEFINITION>
       LoadBalancerInfo:
         ContainerName: "data-apne2-rdd-web-container-sb"
         ContainerPort: 80
