export type { BasicModalProps } from '~/Modal/BasicModal'
export { default as BasicModal } from '~/Modal/BasicModal'
export type { ConfirmModalProps } from '~/Modal/ConfirmModal'
export { default as ConfirmModal } from '~/Modal/ConfirmModal'
export type { ErrorModalProps } from '~/Modal/ErrorModal'
export { default as ErrorModal } from '~/Modal/ErrorModal'
export { default as GlobalModal } from '~/Modal/GlobalModal'
export type { BaseModal, GlobalModalComponent } from '~/Modal/hooks/useModal'
export { default as useModal } from '~/Modal/hooks/useModal'
export type { ModalProps } from '~/Modal/Modal'
export { default as Modal } from '~/Modal/Modal'
export type { SimpleModalProps } from '~/Modal/SimpleModal'
export { default as SimpleModal } from '~/Modal/SimpleModal'
