export type { TextAlign } from '~/Table/Cell'
export type { SimpleTableProps } from '~/Table/SimpleTable'
export { default as SimpleTable } from '~/Table/SimpleTable'
export type { Column, TableProps } from '~/Table/Table'
export { default as Table } from '~/Table/Table'
export { default as TBody } from '~/Table/TBody'
export { default as Td } from '~/Table/Td'
export { default as TFoot } from '~/Table/TFoot'
export { default as Th } from '~/Table/Th'
export { default as THead } from '~/Table/THead'
export { default as Tr } from '~/Table/Tr'
